/**
 * Emitters — panel.json 모델을 Ray 프로젝트 소스로 번역한다.
 *
 * 두 종류를 낸다:
 *  1) 데이터 레이어 (이 파일)  — 모델에서 파생. DP·토큰·문구·링크·라우팅.
 *  2) 고정 템플릿 (templates/) — 실기기 대응 지식이 녹아 있어 모델과 무관하게
 *     검증된 형태로 찍는다. 디바이스 키(`r6`)만 치환한다.
 *
 * 생성물은 사람이 손대는 파일이 아니다 — `dist/` 를 안 고치는 design-guide 규칙과
 * 같다. 값을 바꾸려면 panel.json 을 고치고 다시 생성한다.
 */

const BANNER = '/* AUTO-GENERATED by miniapp-panel-studio — panel.json 에서 생성됨. 직접 고치지 마라. */';

const camel = s => s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
const upperEnum = code => {
  // fan_level -> FAN_LEVELS, mode -> MODES, air_quality -> AIR_QUALITIES
  const base = code.toUpperCase();
  return base.endsWith('S') ? base : base + 'S';
};

/* ── src/config/dpCodes.ts ─────────────────────────────────────────── */
export function emitDpCodes(panel) {
  const lines = [BANNER, '', '/**', ` * ${panel.meta.name} DP codes.`, ' */', 'export default {'];
  for (const dp of panel.dps) {
    const props =
      dp.type === 'enum' ? `Enum ${JSON.stringify(dp.range)}` :
      dp.type === 'value' ? `Value ${dp.min}-${dp.max}, scale ${dp.scale}, unit ${dp.unit}` :
      dp.type === 'string' ? `String maxlen ${dp.maxlen}` :
      dp.type;
    lines.push(`  /** DP ${dp.id} — ${props}, ${dp.mode.toUpperCase()}. */`);
    lines.push(`  ${dp.camel}: '${dp.code}',`);
  }
  lines.push('} as const;', '');

  for (const dp of panel.dps.filter(d => d.type === 'enum' && d.range && d.range.length > 1)) {
    const name = upperEnum(dp.code);
    lines.push(`/** DP ${dp.id} enum. */`);
    lines.push(`export const ${name} = [${dp.range.map(v => `'${v}'`).join(', ')}] as const;`);
    lines.push(`export type ${pascal(dp.camel)} = typeof ${name}[number];`);
    lines.push('');
  }
  return lines.join('\n');
}

/* ── src/devices/schema.ts ─────────────────────────────────────────── */
export function emitSchema(panel) {
  const items = panel.dps.map(dp => {
    const property =
      dp.type === 'enum' ? `{ type: 'enum', range: [${dp.range.map(v => `'${v}'`).join(', ')}] }` :
      dp.type === 'value' ? `{ type: 'value', min: ${dp.min}, max: ${dp.max}, scale: ${dp.scale}, step: ${dp.step}, unit: '${dp.unit}' }` :
      dp.type === 'string' ? `{ type: 'string', maxlen: ${dp.maxlen} }` :
      dp.type === 'fault' ? `{ type: 'fault', label: [${dp.label.map(v => `'${v}'`).join(', ')}] }` :
      `{ type: 'bool' }`;
    return [
      '  {',
      `    id: ${dp.id},`,
      `    code: '${dp.code}',`,
      `    name: '${dp.name}',`,
      `    mode: '${dp.mode}',`,
      `    type: 'obj',`,
      `    property: ${property},`,
      '  },',
    ].join('\n');
  });
  return [
    BANNER,
    '',
    "import _keyBy from 'lodash-es/keyBy';",
    "import { GetSmartDeviceModelDpSchema } from '@ray-js/panel-sdk';",
    '',
    `/** ${panel.meta.name} device schema. */`,
    'export const defaultSchema = [',
    items.join('\n'),
    '] as const;',
    '',
    'export const schemaMap = _keyBy(defaultSchema, \'code\') as GetSmartDeviceModelDpSchema<',
    '  typeof defaultSchema',
    '>;',
    '',
    'export type IDpCodes = keyof typeof schemaMap;',
    '',
  ].join('\n');
}

/* ── src/config/theme.ts ───────────────────────────────────────────── */
export function emitTheme(panel) {
  const t = panel.theme;
  const colorLines = Object.entries(t.color).map(([k, v]) => `  ${k}: '${v}',`);
  const aqLines = Object.entries(t.aqColor).map(([k, v]) => `  ${k === 'very_bad' ? 'very_bad' : k}: '${v}',`);
  const opLines = Object.entries(t.opacity).map(([k, v]) => `  ${k}: ${v},`);
  const note = t.mode?.startsWith('bespoke')
    ? `/**\n * Design tokens.\n *\n * THEME MODE: ${t.mode}\n * REASON: ${t.reason}\n *\n * 이 값들은 hej 시맨틱 토큰이 아니라 실물 하드웨어 표기색이다 (규격 예외).\n */`
    : `/** Design tokens — hej 시맨틱에서 파생. */`;
  return [
    BANNER, '', note,
    'export const COLOR = {',
    ...colorLines,
    '} as const;',
    '',
    'export const AQ_COLOR = {',
    ...aqLines,
    '} as const;',
    '',
    'export const OPACITY = {',
    ...opLines,
    '} as const;',
    '',
  ].join('\n');
}

/* ── src/config/links.ts ───────────────────────────────────────────── */
export function emitLinks(panel) {
  const entries = Object.entries(panel.links || {}).map(
    ([k, v]) => `  /** ${v.desc || ''} */\n  ${k}: '${v.url}',`
  );
  return [
    BANNER, '',
    '/**',
    ' * 앱이 여는 외부 웹 페이지. URL 은 라우트 쿼리로 싣지 않고 키만 넘긴다',
    ' * (openExternal.ts 가 통로를 찾는다). 여는 방식은 panel.json 의 webContent 참고.',
    ' */',
    'export const WEB_LINKS = {',
    ...entries,
    '} as const;',
    '',
    'export type WebLinkKey = keyof typeof WEB_LINKS;',
    '',
    'export function isWebLinkKey(value: unknown): value is WebLinkKey {',
    '  return typeof value === \'string\' && value in WEB_LINKS;',
    '}',
    '',
  ].join('\n');
}

/* ── src/routes.config.ts ──────────────────────────────────────────── */
export function emitRoutes(panel) {
  const items = panel.routes.map(r =>
    `  {\n    route: '${r.route}',\n    path: '${r.path}',\n    name: '${r.name}',\n  },`
  );
  return [
    BANNER, '',
    "import { Routes } from '@ray-js/types';",
    '',
    'export const routes: Routes = [',
    ...items,
    '];',
    '',
  ].join('\n');
}

/* ── src/global.config.ts ──────────────────────────────────────────── */
export function emitGlobalConfig(panel) {
  const fp = panel.meta.functionalPages;
  return [
    BANNER, '',
    "import { GlobalConfig } from '@ray-js/types';",
    "import { COLOR } from '@/config/theme';",
    '',
    'export const tuya = {',
    '  window: {',
    '    backgroundColor: COLOR.bgHome,',
    "    navigationBarTitleText: '',",
    '    navigationBarBackgroundColor: COLOR.bgHome,',
    "    navigationBarTextStyle: 'white',",
    '  },',
    '  functionalPages: {',
    '    settings: {',
    `      appid: '${fp.appid}',`,
    `      entryCode: '${fp.entryCode}',`,
    '    },',
    '  },',
    '};',
    '',
    "const globalConfig: GlobalConfig = { basename: '' };",
    'export default globalConfig;',
    '',
  ].join('\n');
}

/* ── project.tuya.json ─────────────────────────────────────────────── */
export function emitProjectTuya(panel) {
  const p = panel.meta.productTuya;
  return JSON.stringify(
    {
      name: p.name,
      type: p.type,
      ownerType: p.ownerType,
      devMode: p.devMode,
      i18n: false,
      description: '',
      miniprogramRoot: './dist/tuya',
      dependencies: p.dependencies,
      projectname: p.projectname,
      baseversion: p.baseversion,
      compileType: p.compileType,
    },
    null,
    2
  ) + '\n';
}

/* ── src/i18n/strings.ts ───────────────────────────────────────────── */
export function emitStrings(panel) {
  const esc = s => String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  const block = table =>
    Object.entries(table)
      .map(([k, v]) => `    ${k}: '${esc(v)}',`)
      .join('\n');
  const langs = Object.entries(panel.i18n)
    .map(([lang, table]) => `  ${lang}: {\n${block(table)}\n  },`)
    .join('\n');
  return [
    BANNER, '',
    '/** 확정 문구. 키 이름은 동결 — 호출부가 DP enum 으로 키를 조합한다. 값만 고친다. */',
    'export default {',
    langs,
    '};',
    '',
  ].join('\n');
}

/* ── src/res/index.ts ──────────────────────────────────────────────── */
export function emitRes(panel) {
  const imports = panel.icons.map(n => `import ${n} from './${n}.png';`).join('\n');
  const exports = panel.icons.map(n => `  ${n},`).join('\n');
  return [
    BANNER, '',
    '/** 아이콘 자산 레지스트리 — 생성 파일. */',
    imports,
    '',
    'export default {',
    exports,
    '};',
    '',
  ].join('\n');
}

function pascal(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
