/**
 * 고정 템플릿 — 실기기 대응 지식이 박혀 있어 모델과 무관하게 검증된 형태로 찍는다.
 *
 * 여기 담긴 것은 haatz 레포가 실기기에서 피 흘려 얻은 결정들이다:
 *  - `ignoreDpResponse` 를 빼는 이유 (모드 변경 후 5초 센서 리포트 유실)
 *  - `setDps` 배치 전송 (예약이 낡은 시각으로 걸리는 경쟁)
 *  - i18n 지역 별칭 (`ko-KR` → 영어로 떨어지는 SDK 버그)
 *  - openExternal 이중 폴백 (native 모듈 부재)
 *
 * 비개발자는 이 파일들을 건드리지 않는다. 디바이스 키(dk)와 DP 상태 타입만 주입한다.
 */

const dpStateType = panel => {
  const tsType = dp =>
    dp.type === 'bool' ? 'boolean' :
    dp.type === 'value' ? 'number' :
    dp.type === 'string' ? 'string' :
    dp.type === 'color' ? 'string' :  // colour_data raw HSV hex
    dp.type === 'enum' ? dp.range.map(v => `'${v}'`).join(' | ') :
    'unknown';
  const rows = panel.dps
    .filter(dp => dp.semantic !== 'unrendered')
    .map(dp => `  ${dp.camel}?: ${tsType(dp)};`);
  // 렌더 안 하는 DP 는 형만 남긴다 (haatz 의 faultRemind 주석과 같은 취지).
  const unrendered = panel.dps
    .filter(dp => dp.semantic === 'unrendered')
    .map(dp => `  /** DP ${dp.id} — 패널이 소비하지 않는다. 기기가 보내므로 형만 둔다. */\n  ${dp.camel}?: unknown;`);
  return [...rows, ...unrendered].join('\n');
};

export function tplUseDp(panel) {
  const dk = panel.meta.deviceKey;
  return `/* AUTO-GENERATED by miniapp-panel-studio. 디바이스 통신 seam — 실기기 대응 지식 포함. */
import { useDevInfo, useProps } from '@ray-js/panel-sdk';
import { SmartDeviceSchema, devices } from '@/devices';

/** 전 DP 선택. 미보고 DP 는 absent key(undefined). */
export type DpState = {
${dpStateType(panel)}
};

export function useDpState(): DpState {
  return useProps<SmartDeviceSchema, any>() as DpState;
}

/** \`undefined\` until the device model reports otherwise — do not read as offline. */
export function useOnline(): boolean {
  const isOnline = useDevInfo<SmartDeviceSchema>(info => info.isOnline);
  return isOnline !== false;
}

/** Fire-and-forget. offline tap 을 unhandled rejection 으로 띄우지 않는다. */
export function setDp<K extends keyof DpState>(code: K, value: NonNullable<DpState[K]>): void {
  devices.${dk}.publishDps({ [code]: value } as any).catch(() => undefined);
}

/** 여러 DP 를 한 프레임에 — 예약 토글이 낡은 시각으로 걸리는 경쟁을 없앤다. */
export function setDps(dps: Partial<DpState>): void {
  devices.${dk}.publishDps(dps as any).catch(() => undefined);
}
`;
}

export function tplDevicesIndex(panel) {
  const dk = panel.meta.deviceKey;
  return `/* AUTO-GENERATED by miniapp-panel-studio. */
import { SmartDeviceModel, SmartSupportAbility } from '@ray-js/panel-sdk';
import { createDpKit } from '@ray-js/panel-sdk/lib/sdm/interceptors/dp-kit';
import { defaultSchema } from '@/devices/schema';

export type SmartDeviceSchema = typeof defaultSchema;

export const dpKit = createDpKit<SmartDeviceSchema>({
  sendDpOption: {
    // 보낸 DP 를 로컬 상태에 즉시 반영. 낙관적 롤백을 쓰지 않으므로
    // \`ignoreDpDataResponse\` 는 일부러 뺐다 — 그것을 켜면 모든 앱 조작 뒤 5초간
    // 기기의 정당한 센서 리포트가 통째로 유실된다.
    immediate: true,
  },
});

export const devices = {
  ${dk}: new SmartDeviceModel<SmartDeviceSchema, { support: SmartSupportAbility<SmartDeviceSchema> }>({
    interceptors: dpKit.interceptors,
    abilities: [new SmartSupportAbility()],
  }),
};
`;
}

export function tplComposeLayout(panel) {
  const dk = panel.meta.deviceKey;
  return `/* AUTO-GENERATED by miniapp-panel-studio. */
import React, { Component } from 'react';
import { devices, dpKit } from '@/devices';

/** Device-init HOC — onLaunch 가 기기 모델을 먼저 세운다. Redux 없음. */
const composeLayout = (Comp: React.ComponentType<any>) => {
  return class PanelComponent extends Component<any> {
    async onLaunch() {
      devices.${dk}.init();
      devices.${dk}.onInitialized(() => {
        dpKit.init(devices.${dk});
      });
    }
    render() {
      return <Comp {...this.props} />;
    }
  };
};

export default composeLayout;
`;
}

export function tplApp(panel) {
  const dk = panel.meta.deviceKey;
  return `/* AUTO-GENERATED by miniapp-panel-studio. */
import React from 'react';
import '@/i18n';
import { SdmProvider } from '@ray-js/panel-sdk';
import { initPanelEnvironment } from '@ray-js/ray';
import RayErrorCatch from '@ray-js/ray-error-catch';
import { devices } from '@/devices';
import './app.less';
import composeLayout from './composeLayout';

initPanelEnvironment({ useDefaultOffline: true });

class App extends React.Component<{ children: React.ReactNode }> {
  render() {
    return (
      <RayErrorCatch>
        <SdmProvider value={devices.${dk}}>{this.props.children}</SdmProvider>
      </RayErrorCatch>
    );
  }
}

export default composeLayout(App);
`;
}

/** i18n 지역 별칭 로직 — SDK 가 \`ko-KR\` 을 영어로 떨구는 버그를 우리 쪽에서 막는다. */
export function tplI18nIndex() {
  return `/* AUTO-GENERATED by miniapp-panel-studio. panel-sdk 의 지역코드 버그 대응 포함. */
import { kit } from '@ray-js/panel-sdk';
import { getSystemInfoSync } from '@ray-js/ray';
import strings from './strings';

const { I18N } = kit;

const REGIONS: Record<string, string[]> = {
  ko: ['ko-KR', 'ko_KR', 'ko-kr', 'ko_kr'],
  en: ['en-US', 'en_US', 'en-us', 'en_us', 'en-GB', 'en_GB'],
};

function withRegionAliases<T extends Record<string, unknown>>(table: T): T {
  const expanded: Record<string, unknown> = { ...table };
  Object.entries(REGIONS).forEach(([base, variants]) => {
    if (!table[base]) return;
    variants.forEach(v => { expanded[v] = table[base]; });
  });
  return expanded as T;
}

const Strings = new I18N(withRegionAliases(strings));

const systemLang = String(getSystemInfoSync()?.language ?? '');
const base = systemLang.toLowerCase().split(/[-_]/)[0];
if (base && base !== 'en' && (strings as Record<string, unknown>)[base]) {
  Strings.setLanguage(base);
}

export default Strings;
`;
}

/** 외부 URL 열기 — native 모듈 부재에 대비한 이중 폴백. haatz 실기기 검증본. */
export function tplOpenExternal() {
  return `/* AUTO-GENERATED by miniapp-panel-studio. native 모듈 부재 대비 이중 폴백. */
import { openURL, openUrlForceDefaultBrowser } from '@ray-js/ray';

/**
 * 외부 주소를 미니앱 밖에서 연다. openURL(MiniKit) → openUrlForceDefaultBrowser(BizKit)
 * 순으로 시도하고, 둘 다 없으면 onFail. 실패해도 던지지 않는다.
 */
export function openExternal(url: string, onFail: () => void): void {
  openURL({
    url,
    fail: () => openUrlForceDefaultBrowser({ url, fail: onFail }),
  });
}
`;
}

export function tplPackageJson(panel) {
  return JSON.stringify(
    {
      name: panel.meta.id,
      version: '1.0.0',
      license: 'MIT',
      scripts: {
        lint: 'eslint src --ext .js,.jsx,.ts,.tsx --fix',
        'start:tuya': 'ray start -t tuya --verbose',
        'build:tuya': 'ray build -t tuya --verbose',
      },
      dependencies: {
        '@ray-js/panel-sdk': '1.13.1-ignoredp.14',
        '@ray-js/ray': '^1.5.47',
        '@ray-js/ray-error-catch': '^0.0.19',
        '@ray-js/smart-ui': '^2.13.2',
        'core-js': '^3.23.5',
        'lodash-es': '^4.17.21',
      },
      devDependencies: {
        '@ray-js/cli': '^1.5.47',
        '@types/react': '^17.0.24',
        typescript: '^4.4.3',
      },
      resolutions: {
        '@ray-js/panel-sdk': '1.13.1-ignoredp.14',
        '@types/react': '^17.0.24',
        'follow-redirects': '1.15.6',
        '@jridgewell/gen-mapping': '0.3.8',
      },
    },
    null,
    2
  ) + '\n';
}

export function tplRayConfig() {
  return `const config = {\n  resolveAlias: {},\n};\nmodule.exports = config;\n`;
}

export function tplNpmrc() {
  return `# yarn only. resolutions 는 yarn 전용 — npm 은 무시하고 빌드를 깬다.\n`;
}
